apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::159431052044:role/default-eks-node-group-20250916091911108600000001
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::159431052044:user/kergs-admin
      username: kergs-admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::159431052044:user/innovatemart-dev-readonly
      username: innovatemart-dev-readonly
      groups:
        - view
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::159431052044:role/default-eks-node-group-20250916091911108600000001\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n","mapUsers":"- userarn: arn:aws:iam::159431052044:user/kergs-admin\n  username: kergs-admin\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2025-09-18T23:01:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "155569"
  uid: 3b1640ce-bae7-4add-a3da-3412c78db1cd
